version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=piedb
      - DB_USER=pieuser
      - DB_PASSWORD=password123
      - MONGO_URL=mongodb://mongo:27017/pierecipes
      - FRUIT_PICKER_URL=http://fruit-picker-mock:8081
      - BAKER_URL=http://baker-mock:8082
      - DELIVERY_URL=http://delivery-mock:8083
    depends_on:
      - postgres
      - mongo
      - fruit-picker-mock
      - baker-mock
      - delivery-mock

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=piedb
      - POSTGRES_USER=pieuser
      - POSTGRES_PASSWORD=password123
    ports:
      - "5432:5432"

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"

  fruit-picker-mock:
    build:
      context: .
      dockerfile: docker/Dockerfile.mock
    command: node mocks/fruit-picker-mock.js
    ports:
      - "8081:8081"

  baker-mock:
    build:
      context: .
      dockerfile: docker/Dockerfile.mock
    command: node mocks/baker-mock.js
    ports:
      - "8082:8082"

  delivery-mock:
    build:
      context: .
      dockerfile: docker/Dockerfile.mock
    command: node mocks/delivery-mock.js
    ports:
      - "8083:8083"
